project:
    type: book
    output-dir: docs
    post-render: quarto render --profile slides

book:
    title: "Intro to Statistical Modeling"
    author: "Andy Rominger"
    chapters:
        - index.qmd
        - part: intro.qmd
          chapters:
            - datasets-intro.qmd
            - care-fair.qmd
            - r-refresh.qmd
            - dynamic-doc.qmd
            - github.qmd
            - bring-it-together.qmd
        - part: prob.qmd
          chapters:
            - prob-intro.qmd
            - prob-dist.qmd
            - prob-sim-data.qmd
        - part: likelihood-intro.qmd
          chapters:
            - likelihood-lec.qmd
            - binom-lab.qmd
            - norm-lab.qmd
        - part: lin-mod.qmd
          chapters:
            - mods-howto.qmd
            - lin-norm.qmd
            - lin-lstsqrs.qmd
            - rand-effects.qmd
            - rand-effects-lab.qmd
            - mixed-models-lab.qmd
            - binom-glm.qmd
            - binom-glm-lab.qmd
            - pois-glm.qmd
            - pois-glm-lab.qmd
            - overdisp-glm-lab.qmd
        - part: hyp-mod-select.qmd
          chapters:
            - lrt-ci.qmd
            - lrt-lab.qmd


bibliography: stat-mod.bib
csl: conservation-biology.csl

execute:
  freeze: auto

comments:
    hypothesis: false

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 4
