# Linear models

Starting with the simple linear model $y = ax + b + \text{error}$ we will see how we can expand from there, using likelihood methods, to cover many different kinds of ways we might like to model and make inference about biological processes. Models will include multiple linear regression, models where explanatory variables are categorical (i.e. where we might classically use ANOVA), generalized linear models, and mixed effects models.

Jump straight to:

*Simple linear models*

- How to make a model [lecture notes](mods-howto.qmd), [slides](mods-howto-slides.html){target="_blank"}
- [Linear models with normal residuals](lin-norm.qmd)
- [Linear models using R's built-in functions](lin-lstsqrs.qmd)

*Mixed effects models*

- What are random effects? [lecture notes](rand-effects.qmd)
- [Building mixed effects models with *lme4*](rand-effects-lab.qmd)

*Generalized linear models (GLM)*

- The binomial GLM [lecture notes](binom-glm.qmd), [slides](binom-glm-slides.html){target="_blank"}
- The Poisson GLM [slides](pois-glm-slides.html){target="_blank"}
