{
  "hash": "125e551162645806ae0d4d5e159169d8",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat:\n  html:\n    code-links:\n      - text: View source\n        icon: github\n        href: https://github.com/uhm-biostats/stat-mod/blob/main/pois-glm.qmd\nbibliography: stat-mod.bib\ncsl: conservation-biology.csl\n---\n\n\n# The Poisson Generalized Linear Model\n\n\n\n\nIn the previous module we introduced GLMs using the binomial distribution as our example. Recall that the key insight is that different kinds of response variables call for different probability distributions. When data are binary (0/1) or represent proportions, the binomial distribution is appropriate. But what about data that are *counts* such as the number of trees in a plot or the number of species on an island? For these, the ***Poisson distribution*** is a natural choice.\n\n## The Poisson distribution\n\nThe Poisson distribution describes the probability of observing a non-negative, integer count. We write\n\n$$\ny \\sim \\text{Pois}(\\lambda)\n$$\n\nThe parameter $\\lambda$ represents the mean of the distribution, But with only one parameter, we do not have very much flexibility to modulate the variance of the distribution. It turns out the Poisson imposes the strong constraint that the variance is equal to the mean, are both equal to $\\lambda$ (this will be a central point in an upcoming lab). \n\nHere is an example probability mass function for a Poisson distribution with $\\lambda = 4$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# range of count values\nnn <- 0:12\n\nggplot(data.frame(x = nn, y = dpois(nn, 4)), aes(x, y)) +\n    geom_bar(stat = \"identity\") +\n    xlab(expression(italic(y))) +\n    ylab(\"Probability\") +\n    theme_cowplot() +\n    geom_vline(xintercept = 4, color = \"orange\", linewidth = 1.5)\n```\n\n::: {.cell-output-display}\n![](pois-glm_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nBecause $\\lambda$ is both the mean and variance of the distribution, and because counts can never be negative nor can a variance, a critical constraint is that $\\lambda \\geq 0$. This constraint is what drives the need for a special link function in a Poisson GLM.\n\n## The log link function\n\nIn a standard linear model we write the mean response as a linear function of the explanatory variables:\n\n$$\n\\lambda = b_0 + b_1 x\n$$\n\nBut this is a problem for Poisson GLM: a linear combination of predictors can produce any value from $-\\infty$ to $\\infty$, yet $\\lambda$ must be non-negative. The solution is to model the *log* of $\\lambda$ as the linear function:\n\n$$\n\\log(\\lambda) = b_0 + b_1 x\n$$\n\nwhich is equivalent to\n\n$$\n\\lambda = e^{b_0 + b_1 x}\n$$\n\nBecause $e^\\text{anything} \\geq 0$ always, this guarantees that $\\lambda$ will never be negative no matter what values the predictors or coefficients take. The log function is therefore the natural ***link function*** for the Poisson GLM.\n\n## The species–area relationship\n\nYou'll recall that in our [R refresher](r-refresh.qmd) we used the classic species area relationship (SAR) as an example for making data visualizations. To make a model of the SAR, a Poisson GLM might be an appropriate choice, after all number of species (the response variable in the SAR) is a count. One classic form for the (SAR) is expressed as\n\n$$\n\\begin{aligned}\nS &= cA^z \\\\\n\\log(S) &= \\log(c) + z\\log(A)\n\\end{aligned}\n$$\n\nwhere $S$ is the number of species, $A$ is area, $c$ is a constant, and $z$ is the scaling exponent. Log-transforming both sides of the SAR reveals a linear equation...this should perhaps be sounding like a log link function situation. Indeed, if we recognize that we are modeling $\\bar{S}$, the average species richness, then we make these substitutions in the log link funciton equation\n\n\n$$\n\\begin{aligned}\n\\bar{S} &= \\lambda \\\\\n\\log(A) &= x \\\\\nb_0 &= \\log(c)  \\\\\nb_1 &= z\n\\end{aligned}\n$$\n\nand we arrive at a log link function for $\\bar{S}$:\n\n$$\n\\log(\\bar{S}) = b_0 + b_1 \\log(A)\n$$\n\nLet's visualize the data (note: we are excluding the two *very* large survey plots because they are extreme outliers on the x-axis)\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](pois-glm_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nOn the log–log scale we see a roughly linear relationship, consistent with the SAR and log link assumptions of Poisson GLM.\n\n## Fitting a Poisson GLM in R\n\nFitting a Poisson GLM in R again uses the `glm` function, just as with the binomial GLM. The key difference is specifying `family = poisson`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# note: i've done some data wrangling alread to make the\n# object `dat_plt`\nhead(dat_plt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PlotID Plot_Area avg_temp_annual_c hii nspp\n1      1   1000.00          19.90869  38    9\n2      2   1017.88          22.25223  22    9\n3      3   1017.88          22.25223  22    2\n4      4   1017.88          22.25223  22    9\n5      5   1017.88          22.25223  22    4\n6      6   1017.88          22.25223  22    9\n```\n\n\n:::\n\n```{.r .cell-code}\n# here is the model\nsar <- glm(nspp ~ log(Plot_Area),\n           data = dat_plt,\n           family = poisson)\n```\n:::\n\n\nNote that we only need to log-transform the *explanatory* variable (`Plot_Area`). The log link function automatically handles the log-transformation of the *mean* of the response. We do not need to log-transform `nspp`. We can inspect the coefficients as usual:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefficients(sar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept) log(Plot_Area) \n    -1.8086075      0.4893528 \n```\n\n\n:::\n:::\n\n\n\n\n\nWe can plug these into the SAR equation:\n\n$$\nS = e^{-1.809} A^{0.489}\n$$\n\n\n## Adding more explanatory variables\n\nArea is a natural starting point for modeling species richness, but we are likely interested in additional predictors. In fact, area might even be a *nuisance variable*---one we need to account for statistically, but that is not our main scientific interest. We might be more interested in, say, human impact (`hii`) or temperature (`avg_temp_annual_c`).\n\nAdding more predictors to a Poisson GLM is no different from adding them to a linear model---just extend the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- glm(nspp ~ log(Plot_Area) + hii + avg_temp_annual_c,\n           data = dat_plt,\n           family = poisson)\n\ncoefficients(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      (Intercept)    log(Plot_Area)               hii avg_temp_annual_c \n     -2.320992411       0.516567381       0.011011301       0.007295895 \n```\n\n\n:::\n:::\n\n\nAfter accounting for plot area, species richness appears to increase (weakly) with both human impact index and mean annual temperature. Given our conservation concern about human impact, this might not make sense at first. However, there is at least some scientific thought that non-native plants augment species richness [@sax2003] and thus heavily impacted sites have many introduced species that add to the total count. However, the other part of the story is temperature---hotter areas have more species. This could be because lowland areas are hotter and also more likely to be impacted by humans. But it is also worth noting that, historically, hot and dry lowland forests were once incredibly diverse with unique endemic species [@rock1913] that are indeed now being lost by human impact. It is also worth taking a moment to contemplate the @rock1913 publication. Rock was a botanist paid by the American government to survey plants in Hawaiʻi. 1913 is only 30 years after the 1893 illegal overthrow of the Hawaiian Kingdom. While @rock1913 provides a convenient citation, his work also represents science as colonialism and colonialism as science.\n\n## Collinearity\n\nAt a much more trivial level---in terms of ethics and biology---adding more explanatory variables requires care. When two or more predictors are *correlated* with each other, we run into ***collinearity***, and that causes problems for estimation.\n\nTo see why, we can visualize the likelihood surface for the slopes of human impact and temperature from the model above:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](pois-glm_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nInstead of a well-defined peak, the likelihood surface has a long, flat ***ridge***, meaning many---infinite---combinations of the two slope coefficients have nearly the same likelihood. That makes it difficult and unreliable to identify the unique best-fitting parameter values.\n\nWhen we visualize human impact and temperature we see they are indeed correlated with each other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat_plt, aes(hii, avg_temp_annual_c)) +\n    geom_point() +\n    xlab(\"Human impact index\") +\n    ylab(\"Mean annual temperature (C)\") +\n    theme_cowplot()\n```\n\n::: {.cell-output-display}\n![](pois-glm_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\nThe practical takeaway: before including multiple predictors in a model, check for pairwise correlations among them. A commonly used guideline is to only include predictors with pairwise correlation coefficients $-0.6 < r < 0.6$. You can compute correlations with `cor()` in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(dat_plt$hii, dat_plt$avg_temp_annual_c, use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6397327\n```\n\n\n:::\n:::\n\n\nIf two predictors are too highly correlated, you will typically need to choose one or the other, or find a way to combine them, such as through principal component analysis or other dimension reduction techniques, rather than including both in the same model.\n\n\n## Slides {#sec-slides}\n\n\n```{=html}\n<iframe class=\"slide-deck\" src=\"pois-glm-slides.html\"></iframe>\n```\n\n## References\n",
    "supporting": [
      "pois-glm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}