{
  "hash": "56b53e42018487f62487252ba9dc84e0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Null hypothesis testing considerations and connections\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n## The GLM\n\nWe've been working with models like\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsar_mod <- glm.nb(nspp ~ log(Plot_Area), data = dat_plt)\n```\n:::\n\n\n::: {.fragment}\n\n<br>\nAnd testing \"significance\" with a likelihood ratio test (LRT)\n\n:::\n\n\n::: {.fragment}\n\n<br>\nBut there are other approaches, perhaps some that seem more familiar\n\n:::\n\n## The GLM {.scrollable}\n\nThe `summary` function gives us a lot of info (scroll down)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sar_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = nspp ~ log(Plot_Area), data = dat_plt, init.theta = 9.014755177, \n    link = log)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -1.75853    0.33458  -5.256 1.47e-07 ***\nlog(Plot_Area)  0.48172    0.05051   9.537  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(9.0148) family taken to be 1)\n\n    Null deviance: 622.95  on 527  degrees of freedom\nResidual deviance: 515.85  on 526  degrees of freedom\nAIC: 2331.3\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  9.01 \n          Std. Err.:  1.76 \n\n 2 x log-likelihood:  -2325.269 \n```\n\n\n:::\n:::\n\n\n\n## The GLM \n\nSome of this info in fact directly relates to the LRT\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n    Null deviance: 622.95  on 527  degrees of freedom\nResidual deviance: 515.85  on 526  degrees of freedom\n```\n\n\n:::\n:::\n\n\n\n::: {.fragment}\n\n(`527` d.f.) - (`526` d.f.) = 1 d.f., the right number if we were comparing models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_full <- nspp ~ log(Plot_Area)\nmod_reduced <- nspp ~ 1\n```\n:::\n\n\n:::\n\n\n::: {.fragment}\n\nThe LRT statistic for those two models is\n\n\n::: {.cell}\n\n:::\n\n\n$$\n\\begin{aligned}\n\\Lambda &= 2 (\\log\\mathscr{L}_\\text{full} - \\log\\mathscr{L}_\\text{reduced}) \\\\\n&= 98.88\n\\end{aligned}\n$$\n\nwhich is (approx.) equal to `622.95 - 515.85`\n\n(approx. because printed summary for `glm.nb` is a little strange)\n\n:::\n\n\n\n## The GLM \n\nWhat's going on?\n\n::: {.fragment}\n\nThe *deviance* is an attempt to generalize the idea of *\"sum of squares\"*\n\n:::\n\n\n::: {.fragment}\n\n$$\n\\begin{aligned}\n\\text{Null deviance} &= 2 (\\log\\mathscr{L}_\\text{saturated} - \\log\\mathscr{L}_\\text{reduced}) \\\\\n\\text{Residual deviance} &= 2 (\\log\\mathscr{L}_\\text{saturated} - \\log\\mathscr{L}_\\text{full})\n\\end{aligned}\n$$\nWhere $\\log\\mathscr{L}_\\text{saturated}$ is the log likelihood of a model where every data point gets a parameter (i.e. its the highest possible log likelihood)\n:::\n\n\n## The GLM \n\nWhat's going on?\n\n::: {.columns}\n\n\n:::: {.column width=30%}\n\n*Null deviance* \n\n<br>\n\n*Residual deviance*\n\n::::\n\n:::: {.column width=70%}\n\n\ncorresponds to \"total sum of squares\" in a least squares world\n\n\ncorresponds to \"residual sum of squares\"\n\n::::\n\n\n:::\n\n::: {.fragment}\n\nIn least squares world we do an $F$-test (aka ANOVA) which compares residual and total sums of squares\n\n:::\n\n::: {.fragment}\n\n<br>\nIn likelihood world we do an LRT (perhaps with function `anova`) which compares residual and null deviances\n\n:::\n\n\n## The GLM versus the LM\n\nThe only difference between a GLM and LM is an LM assumes normality\n\n\n::: {.fragment}\n\nIt is a mathematical novelty that under normality, \n\n\n::: {.columns}\n\n:::: {.column width=45%}\n\n::: {style=\"text-align: right;\"}\n\nleast squares \n\nminimize sum of squares residual \n\n$P$-value of SumSq ANOVA\n\n:::\n\n::::\n\n:::: {.column width=10%}\n\n::: {style=\"text-align: center;\"}\n\n$\\Longleftrightarrow$\n\n$\\Longleftrightarrow$\n\n<br>\n$=$\n\n::: \n\n::::\n\n:::: {.column width=45%}\n\nmaximum likelihood\n\nmaximize log likelihood function\n\n$P$-value of LRT\n\n::::\n\n:::\n\n:::\n\n\n## The GLM \n\nThe `summary` function also gave $P$-values\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -1.75853    0.33458  -5.256 1.47e-07 ***\nlog(Plot_Area)  0.48172    0.05051   9.537  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWhat are those about?\n\n::: {.fragment .incremental}\n\n- Those come from the asymptotic (CLT) behavior of maximum likelihood estimates being normally distributed\n- They are generally not as robust as the $t$-test we can do for LM with normality assumption\n- The LRT is preferred for significance testing\n\n:::\n\n\n## The mixed effects model\n\nRecall for a mixed effects model we did not get any $P$-values despite `summary` reporting $t$-values ($t$ as in $T$-test)\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\n\nmixed_mod <- lmer(log_dbh_cm ~ Native_Status * hii + (1 | PlotID), \n                  data = dat, REML = FALSE)\n\nsummary(mixed_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood  ['lmerMod']\nFormula: log_dbh_cm ~ Native_Status * hii + (1 | PlotID)\n   Data: dat\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n  66659.5   66711.3  -33323.8   66647.5     41447 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3415 -0.6791 -0.0499  0.5649  4.8794 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n PlotID   (Intercept) 0.1367   0.3697  \n Residual             0.2818   0.5309  \nNumber of obs: 41453, groups:  PlotID, 530\n\nFixed effects:\n                         Estimate Std. Error t value\n(Intercept)              2.354021   0.050752  46.383\nNative_Statusnative      0.619260   0.040328  15.356\nhii                      0.000556   0.002294   0.242\nNative_Statusnative:hii -0.007436   0.001750  -4.249\n\nCorrelation of Fixed Effects:\n            (Intr) Ntv_St hii   \nNtv_Sttsntv -0.603              \nhii         -0.915  0.488       \nNtv_Sttsnt:  0.540 -0.949 -0.478\n```\n\n\n:::\n:::\n\n\n\n## The mixed effects model\n\nHere again an LRT is the better option\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a model to single out the interaction term\nreduced_mod <- lmer(log_dbh_cm ~ Native_Status + hii + (1 | PlotID), \n                  data = dat, REML = FALSE)\n\n# the LRT\nanova(mixed_mod, reduced_mod, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat\nModels:\nreduced_mod: log_dbh_cm ~ Native_Status + hii + (1 | PlotID)\nmixed_mod: log_dbh_cm ~ Native_Status * hii + (1 | PlotID)\n            npar   AIC   BIC logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nreduced_mod    5 66676 66719 -33333     66666                         \nmixed_mod      6 66660 66711 -33324     66648 18.033  1  2.171e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "hyp-test-recap-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}