{
  "hash": "447ff512287d47892bb195c3fe1d62d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat:\n  html:\n    code-links:\n      - text: View source\n        icon: github\n        href: https://github.com/uhm-biostats/stat-mod/blob/main/hyp-test-recap.qmd\nbibliography: stat-mod.bib\ncsl: conservation-biology.csl\n---\n\n\n# Null hypothesis testing considerations and connections\n\n\n\nThroughout this module we have been fitting GLMs such as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsar_mod <- glm.nb(nspp ~ log(Plot_Area), data = dat_plt)\n```\n:::\n\n\nand testing significance with the likelihood ratio test (LRT). But GLMs also produce output that may look more familiar, and it is worth understanding exactly how that output connects to everything we have been doing with likelihoods.\n\n## What `summary` tells you\n\nThe `summary` function produces a dense table of information:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sar_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = nspp ~ log(Plot_Area), data = dat_plt, init.theta = 9.014755177, \n    link = log)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -1.75853    0.33458  -5.256 1.47e-07 ***\nlog(Plot_Area)  0.48172    0.05051   9.537  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(9.0148) family taken to be 1)\n\n    Null deviance: 622.95  on 527  degrees of freedom\nResidual deviance: 515.85  on 526  degrees of freedom\nAIC: 2331.3\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  9.01 \n          Std. Err.:  1.76 \n\n 2 x log-likelihood:  -2325.269 \n```\n\n\n:::\n:::\n\n\nTwo particular lines near the bottom are worth unpacking:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n    Null deviance: 622.95  on 527  degrees of freedom\nResidual deviance: 515.85  on 526  degrees of freedom\n```\n\n\n:::\n:::\n\n\nThese are the ***null deviance*** and ***residual deviance***. To understand what they mean, we need to introduce the saturated model: a hypothetical model with one free parameter for every data point, so it achieves the highest possible log-likelihood. Call its log-likelihood $\\log\\mathscr{L}_\\text{saturated}$. Then:\n\n$$\n\\begin{aligned}\n\\text{Null deviance} &= 2\\,(\\log\\mathscr{L}_\\text{saturated} - \\log\\mathscr{L}_\\text{reduced}) \\\\\n\\text{Residual deviance} &= 2\\,(\\log\\mathscr{L}_\\text{saturated} - \\log\\mathscr{L}_\\text{full})\n\\end{aligned}\n$$\n\nwhere \"reduced\" means the intercept-only model (`nspp ~ 1`) and \"full\" means the model we actually fitted (`nspp ~ log(Plot_Area)`). Deviance is therefore a likelihood-based measure of how far a model is from a perfect fit. The larger the deviance, the worse the model fits relative to the theoretical maximum.\n\n## Deviance and the LRT\n\nThe connection to the LRT becomes clear when we subtract:\n\n$$\n\\text{Null deviance} - \\text{Residual deviance} = 2\\,(\\log\\mathscr{L}_\\text{full} - \\log\\mathscr{L}_\\text{reduced})\n$$\n\nThat difference is precisely the LRT statistic $\\Lambda$! We can verify this numerically:\n\n\n::: {.cell}\n\n:::\n\n\n$$\n\\begin{aligned}\n\\Lambda &= 2\\,(\\log\\mathscr{L}_\\text{full} - \\log\\mathscr{L}_\\text{reduced}) \\\\\n        &= 98.88\n\\end{aligned}\n$$\n\nwhich is approximately equal to `622.95 - 515.85` from the printed summary (the small discrepancy is because the printed deviances for `glm.nb` are slightly rounded).\n\nThe degrees of freedom reported alongside the deviances — `527` for null and `526` for residual — also tell the right story: (527 df) − (526 df) = 1, matching the one extra parameter (`log(Plot_Area)`) we added to go from the reduced to the full model.\n\n## Connection to least squares and the $F$-test\n\nIf this structure feels reminiscent of a least-squares ANOVA table, that is not a coincidence. Deviance is the likelihood-world generalization of sums of squares:\n\n| Least squares | Likelihood |\n|---|---|\n| Total sum of squares | Null deviance |\n| Residual sum of squares | Residual deviance |\n| $F$-test (ANOVA) | LRT |\n\nIn a least-squares analysis we test significance by comparing the residual sum of squares to the total sum of squares via an $F$-test. In the likelihood framework we do the same thing by comparing the residual deviance to the null deviance via the LRT.\n\n## The special case of normal errors\n\nA linear model with normally distributed errors is just a GLM where the distribution happens to be normal. Under normality, something mathematically elegant occurs: least squares and maximum likelihood are exactly equivalent. Minimizing the sum of squared residuals gives exactly the same parameter estimates as maximizing the log-likelihood. As a consequence, the $p$-value from a sum-of-squares $F$-test is identical to the $p$-value from the corresponding LRT. The two approaches are not merely analogous under normality — they are the same test.\n\nFor non-normal GLMs (Poisson, negative binomial, binomial) there is no such equivalence, and we rely on the asymptotic $\\chi^2$ approximation of the LRT.\n\n## The $z$-values in `summary`\n\nGoing back to the `summary` output, there is another block of numbers that deserves attention:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -1.75853    0.33458  -5.256 1.47e-07 ***\nlog(Plot_Area)  0.48172    0.05051   9.537  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThese are $z$-values (and associated $p$-values) for each coefficient individually, produced by dividing each estimate by its standard error. They come from a different theoretical justification: the central limit theorem tells us that MLEs are approximately normally distributed in large samples, so each estimate divided by its standard error should behave like a standard normal deviate. This is called a ***Wald test***.\n\nThe Wald $p$-values are convenient because they are computed directly from the `summary` output without fitting any additional models. However, they are generally less reliable than the LRT, especially for small samples or when the log-likelihood surface is not well-approximated by a quadratic. For testing whether a predictor improves the model, the LRT is the preferred approach. The `summary` $z$-values are most useful as a quick diagnostic to see which parameters look roughly significant before committing to a full LRT comparison.\n\n## Mixed effects models and the absence of $p$-values\n\nRecall that when we fit a mixed effects model with `lmer`, the `summary` output reports $t$-values for the fixed effects but conspicuously omits $p$-values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- left_join(tree, geo_hii) |>\n    filter(!is.na(DBH_cm)) |>\n    mutate(log_dbh_cm = log(DBH_cm)) |>\n    filter(!is.na(hii)) |>\n    filter(Native_Status != \"uncertain\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(PlotID)`\n```\n\n\n:::\n\n```{.r .cell-code}\nmixed_mod <- lmer(log_dbh_cm ~ Native_Status * hii + (1 | PlotID),\n                  data = dat, REML = FALSE)\n\nsummary(mixed_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood  ['lmerMod']\nFormula: log_dbh_cm ~ Native_Status * hii + (1 | PlotID)\n   Data: dat\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n  66659.5   66711.3  -33323.8   66647.5     41447 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3415 -0.6791 -0.0499  0.5649  4.8794 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n PlotID   (Intercept) 0.1367   0.3697  \n Residual             0.2818   0.5309  \nNumber of obs: 41453, groups:  PlotID, 530\n\nFixed effects:\n                         Estimate Std. Error t value\n(Intercept)              2.354021   0.050752  46.383\nNative_Statusnative      0.619260   0.040328  15.356\nhii                      0.000556   0.002294   0.242\nNative_Statusnative:hii -0.007436   0.001750  -4.249\n\nCorrelation of Fixed Effects:\n            (Intr) Ntv_St hii   \nNtv_Sttsntv -0.603              \nhii         -0.915  0.488       \nNtv_Sttsnt:  0.540 -0.949 -0.478\n```\n\n\n:::\n:::\n\n\nThis is intentional. For mixed effects models the degrees of freedom for a $t$-test are ambiguous — it is not clear how to count the effective sample size when observations are grouped. The `lme4` authors deliberately omit $p$-values rather than report ones that might be badly calibrated.\n\nThe LRT sidesteps this issue entirely. Because it works with log-likelihoods rather than degrees of freedom for a $t$-distribution, it remains well-calibrated for mixed models as long as we use maximum likelihood (not REML) estimation. Here is the LRT for testing the interaction term:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced_mod <- lmer(log_dbh_cm ~ Native_Status + hii + (1 | PlotID),\n                    data = dat, REML = FALSE)\n\nanova(mixed_mod, reduced_mod, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat\nModels:\nreduced_mod: log_dbh_cm ~ Native_Status + hii + (1 | PlotID)\nmixed_mod: log_dbh_cm ~ Native_Status * hii + (1 | PlotID)\n            npar   AIC   BIC logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nreduced_mod    5 66676 66719 -33333     66666                         \nmixed_mod      6 66660 66711 -33324     66648 18.033  1  2.171e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe LRT compares the full model (with the `Native_Status × hii` interaction) to the reduced model (without it). The resulting $\\chi^2$ statistic and $p$-value do not require any assumptions about degrees of freedom beyond the difference in the number of parameters — which is simply the number of terms dropped.\n\n\n## Slides {#sec-slides}\n\n\n```{=html}\n<iframe class=\"slide-deck\" src=\"hyp-test-recap-slides.html\"></iframe>\n```\n\n## References\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}